### ISSUE TITLE
the output image is automately removed??

### ISSUE THREAD

**Issue by gwontaeyong** [kerberos-io/docker#12]
Now i was running 4 docker container in virtual machine. 
The kerbero.io is running very well. when some moved detected it save a image.
but after a few minute. That image was removed.  

https://kerberosio.zendesk.com/hc/en-us/articles/202842272-Images-are-deleted-when-partition-is-almost-full

i was saw this answer. in this page you say if the disk is full the image will be removed automatically.
but this case is occured in kios. 

this remove the image algorithm is same with docker?

**Comment by cedricve** [comment]
Yes, it's integrated. 

Can you open a session to the docker container and write "df -h"?

**Comment by gwontaeyong** [comment]
Yes as you told i write "dh -h" 
The disk is almost full. Thank you
