### ISSUE TITLE
docker: no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by JulyIghor** [kerberos-io/docker#20]
```
docker run --name KerberOS -p 80:80 -p 8889:8889 -d kerberos/kerberos
Unable to find image 'kerberos/kerberos:latest' locally
latest: Pulling from kerberos/kerberos
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
```

**Comment by cedricve** [comment]
which device are you using?

**Comment by JulyIghor** [comment]
Jetson Nano

**Comment by cedricve** [comment]
Trying to  create a build. However arm64 is already available, but the v8 might be a specific archutecture? @JulyIghor

**Comment by JulyIghor** [comment]
If I manually tag it, it works, It is just :latest tag not worked

**Comment by cedricve** [comment]
@JulyIghor so you had to define the sha256  tag?

**Comment by JulyIghor** [comment]
> @JulyIghor so you had to define the sha256 tag?

sorry I don't remember, I don't have this device any more
