### ISSUE TITLE
image tags for each version

### ISSUE THREAD

**Issue by leeallen337** [kerberos-io/docker#29]
I was looking at the [tag list](https://hub.docker.com/r/kerberos/kerberos/tags) for the docker containers and I was wondering if you plan on adding tags for the [releases](https://doc.kerberos.io/opensource/releases). Something like `2.8.0` in addition to having `latest` or `master`? That would support using a specific version and upgrading the version when desired as opposed to always pulling the latest, which could be newer versions I assume? Thanks!

**Comment by cedricve** [comment]
hey @leeallen337, in the past we had two docker containers, and merge them to one. Once we release an new version this is indeed the way to version. Thanks for sharing ;)
