### ISSUE TITLE
Multi-architecture support

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/docker#3]
# Context
We're creating a ARM Dockerfile, so Kerberos.io can also be used on other architectures as well. Afterwards we can use a manifest tool (http://container-solutions.com/multi-arch-docker-images/) to redirect to architecture specific images.  

# Registry
~~Currently the only way is to create separate tags to support different architectures (e.g. machinery-x86, machinery-armv7hf, machineryamd64, etc). This is not clean, therefore Docker is creating an OOTB implementation to support this feature. To be continued.~~

~~docker/docker/pull/27455~~

# Manifest tool
We're using Docker's Edge feature **docker manifest** to map the different architectures.

**Comment by cedricve** [comment]
@dragoncube we can proceed in here.

**Comment by IulianParaian** [comment]
Hi @cedricve ,
I am trying to build the docker image on a rpi3 device but I'm getting the folowing error:
`
Step 3/12 : RUN cross-build-start
 ---> Running in eb11c1cebd50
standard_init_linux.go:178: exec user process caused "exec format error"
The command 'cross-build-start' returned a non-zero code: 1
`
I also tried with 'FROM resin/raspberrypi3-debian' but I get the same error.

**Comment by cedricve** [comment]
We're using Docker's Edge feature **docker manifest** to map the different architectures. Already compiled the different bases. 

https://github.com/kerberos-io/docker/tree/master/base-linux-amd64
https://github.com/kerberos-io/docker/tree/master/base-linux-arm

**Comment by cedricve** [comment]
we're now manifesting the kerberos/kerberos image.
https://hub.docker.com/r/kerberos/kerberos
